brew "clang-format"
brew "fd"
brew "git"
brew "lua-language-server"
brew "rg"
brew "shfmt"
brew "tree-sitter-cli"

cask "font-caskaydia-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "font-jetbrains-mono-nerd-font"
